Trainingfile = open("Training.txt", "w")
Trainingfile.write('''****PYTHTON TRAINING BY SURESH SIR****\nPYTHON INTRO\nPYTHON VARIABLES\nPYTHON DATA TYPES\nPYTHON STRINGS\nPYTHON BOOLEANS\nPYTHON OPERATORS\nPYTHON LIST\nPYTHON TUPLES\nPYTHON DICTIONARIES\nPYTHON IF ELSE\nPYTHO INHERITANCE\nPYTHON MODULE\nPYTHON FILE HANDLING\nETC..''')
Trainingfile.close()
